-- Baseline schema: matches what Hibernate generated from the entities
-- (Product, User) before Flyway took over schema management.

CREATE TABLE products (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR(255)     NOT NULL,
    price    DOUBLE PRECISION NOT NULL,
    category VARCHAR(255)     NOT NULL,
    stock    INTEGER          NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN'))
);
